### ISSUE TITLE
TBI: Update the readme file

### ISSUE THREAD

**Issue by dhirajwork** [dhirajwork/OSSE-ASSIGNMENT#1]
This task require you to update the readme file with relevant context regarding the project.

Use markdown , bullets , emojis, image , links.

At the end of this task user must be able to understand about our project by going through the readme file.

**Comment by RAVIGANESHMBHAT** [comment]
I added my part of content to the ReadMe.md file.

**Comment by ShwetaGolani** [comment]
My part of ReadMe added.
