### ISSUE TITLE
TBI: Implement the login screen

### ISSUE THREAD

**Issue by RAVIGANESHMBHAT** [dhirajwork/OSSE-ASSIGNMENT#4]
Implement the login screen with email and password.

Give option for Sign Up and Forgot password.

The page must be flexible enough to adapt to the change of screen sizes.

**Comment by dhirajwork** [comment]
This has been implemented. Can you please close this?

**Comment by dhirajwork** [comment]
@RAVIGANESHMBHAT

**Comment by RAVIGANESHMBHAT** [comment]
Looks good. Thanks.
