### ISSUE TITLE
TBI: Create an API end-point for the home page

### ISSUE THREAD

**Issue by RAVIGANESHMBHAT** [dhirajwork/OSSE-ASSIGNMENT#5]
The url must navigate to the home screen of hotel reservation application.

The page must list down all the reservations done by the logged in user.
An option must be given for the user to create a new reservation.

**Comment by dhirajwork** [comment]
@RAVIGANESHMBHAT I have completed the development. Please close this issue.

**Comment by RAVIGANESHMBHAT** [comment]
Good. Thanks for the contribution.
